Repository AnswerDotAI/fastcore, pull requests merged in 2022-08, with the labels that each got.

#454 convert `xdg` to a notebook
  fastcore/_modidx.py
  fastcore/xdg.py
  nbs/09_xdg.ipynb
  nbs/_quarto.yml
  nbs/styles.css
Labels: documentation

#455 in-memory `Config` by passing `save=False`
  fastcore/foundation.py
  nbs/02_foundation.ipynb
Labels: enhancement

#456 layered `Config` with `extra_files`; `Config` `repr`
  fastcore/foundation.py
  nbs/02_foundation.ipynb
Labels: enhancement

#451 New method: `AttrDict.copy`, to return AttrDict instead of plain python dict
  fastcore/_modidx.py
  fastcore/basics.py
  nbs/01_basics.ipynb
Labels: enhancement

#460 Add `fastcore.style`: fast styling for friendly CLIs
  .gitignore
  fastcore/_modidx.py
  fastcore/style.py
  nbs/10_style.ipynb
Labels: enhancement

#462 fix `fastcore.style` format resets and auto-complete
  fastcore/style.py
  nbs/10_style.ipynb
Labels: bug
