Repository AnswerDotAI/fastcore, pull requests merged in 2024-08, with the labels that each got.

#597 Allow embedding raw HTML inside FT templates using UTF-8 encoded bytes
  fastcore/xml.py
  nbs/11_xml.ipynb
Labels: enhancement

#612 move patched methods to parent class
  fastcore/_modidx.py
  fastcore/py2pyi.py
  nbs/12_py2pyi.ipynb
  nbs/test_py2pyi.pyi
Labels: enhancement

#613 fix annotations generated by py2pyi
  fastcore/py2pyi.py
  nbs/12_py2pyi.ipynb
  nbs/test_py2pyi.pyi
Labels: bug

#616 Add to flexiclass docs
  fastcore/basics.py
  fastcore/dispatch.py
  fastcore/docments.py
  fastcore/foundation.py
  fastcore/meta.py
  fastcore/net.py
  fastcore/parallel.py
  fastcore/script.py
  fastcore/style.py
  fastcore/test.py
  fastcore/transform.py
  fastcore/xdg.py
  fastcore/xml.py
  fastcore/xtras.py
  nbs/03_xtras.ipynb
Labels: documentation
